// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnEeMLnnj3CWtlj4tIVMC5eCqQXSVzcC0',
    appId: '1:106607248834:web:45e9775d64ccc9f15e025b',
    messagingSenderId: '106607248834',
    projectId: 'kidquest-e23a0',
    authDomain: 'kidquest-e23a0.firebaseapp.com',
    storageBucket: 'kidquest-e23a0.firebasestorage.app',
    measurementId: 'G-GJVBV42DER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWG9Hvupbsv6mzo9_I8ISxOnlshrFKfIM',
    appId: '1:106607248834:android:4a3c02573f7314225e025b',
    messagingSenderId: '106607248834',
    projectId: 'kidquest-e23a0',
    storageBucket: 'kidquest-e23a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXLmsF5zWKVCrgzoMNvgeqByNHsUrQhCY',
    appId: '1:106607248834:ios:0b755a4668b93f705e025b',
    messagingSenderId: '106607248834',
    projectId: 'kidquest-e23a0',
    storageBucket: 'kidquest-e23a0.firebasestorage.app',
    iosBundleId: 'com.example.kidquest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXLmsF5zWKVCrgzoMNvgeqByNHsUrQhCY',
    appId: '1:106607248834:ios:0b755a4668b93f705e025b',
    messagingSenderId: '106607248834',
    projectId: 'kidquest-e23a0',
    storageBucket: 'kidquest-e23a0.firebasestorage.app',
    iosBundleId: 'com.example.kidquest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnEeMLnnj3CWtlj4tIVMC5eCqQXSVzcC0',
    appId: '1:106607248834:web:e339d0aa2e1f2e655e025b',
    messagingSenderId: '106607248834',
    projectId: 'kidquest-e23a0',
    authDomain: 'kidquest-e23a0.firebaseapp.com',
    storageBucket: 'kidquest-e23a0.firebasestorage.app',
    measurementId: 'G-HWM40QN71F',
  );
}
