class RoutineTemplates {
  static List<Map<String, dynamic>> getTasks(String childId) {
    return [
      {
        "title": "Wake Up",
        "description": "Wake up before 7:15 AM",
        "submissionTime": "07:15",
        "xp": 20,
        "coins": 4,
        "icon": "wb_sunny",
        "color": "#FFD54F",
      },
      {
        "title": "Fresh Up",
        "description": "Brush & Fresh up before school",
        "submissionTime": "07:45",
        "xp": 15,
        "coins": 3,
        "icon": "shower",
        "color": "#4FC3F7",
      },
      {
        "title": "Breakfast",
        "description": "Finish breakfast",
        "submissionTime": "08:00",
        "xp": 15,
        "coins": 3,
        "icon": "breakfast_dining",
        "color": "#FFB74D",
      },
      {
        "title": "Return from School",
        "description": "Come home before 5 PM",
        "submissionTime": "17:00",
        "xp": 30,
        "coins": 6,
        "icon": "school",
        "color": "#81C784",
      },
      {
        "title": "Evening Fresh Up",
        "description": "Fresh up after school",
        "submissionTime": "18:00",
        "xp": 15,
        "coins": 3,
        "icon": "shower",
        "color": "#4DD0E1",
      },
      {
        "title": "Homework",
        "description": "Complete today's homework",
        "submissionTime": "20:00",
        "xp": 30,
        "coins": 6,
        "icon": "menu_book",
        "color": "#BA68C8",
      },
      {
        "title": "Dinner",
        "description": "Finish dinner",
        "submissionTime": "20:30",
        "xp": 20,
        "coins": 4,
        "icon": "dinner_dining",
        "color": "#EF5350",
      },
      {
        "title": "Today's New Word",
        "description": "Learn one new English word",
        "submissionTime": "20:40",
        "xp": 25,
        "coins": 5,
        "icon": "auto_stories",
        "color": "#5C6BC0",
      },
      {
        "title": "Go To Bed",
        "description": "Sleep before 8:45 PM",
        "submissionTime": "20:45",
        "xp": 20,
        "coins": 4,
        "icon": "bed",
        "color": "#9575CD",
      },
    ];
  }
}